version: "2"

services:
  api:
    container_name: "user-api"
    image: "python:latest"
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - "mongo"
    command: "bash -c 'pip install -r requirements.txt && python src/app.py'"
    ports:
      - "8080:5000"
    environment:
      - "PORT=5000"
      - "MONGODB_CONNECTION_URL=mongodb://mongo:27017/"
      - "DB_NAME=user-db"

  mongo:
    image: "mongo:latest"
    expose:
      - "27017"
